### ISSUE TITLE
Icons meaning

### ISSUE THREAD

**Issue by bceppi** [sobolevn/sobole-zsh-theme#10]
First of all thanks for the theme, I liked it a lot.

Where can I get info about the icons meaning?

For example, when working on git I sometimes see a star, a red thunderbolt with a number, etc. but I don't understand what their meaning is, and couldn't find anything related.

**Comment by sobolevn** [comment]
Thanks! Indeed, I should document that. Right now you can have a look at these lines:

https://github.com/sobolevn/sobole-zsh-theme/blob/master/sobole.zsh-theme#L110-L115

I will add annotations shortly.

**Comment by sobolevn** [comment]
Does [it answer](https://github.com/sobolevn/sobole-zsh-theme#indications) your question now? Feel free to reopen if needed.

**Comment by bceppi** [comment]
That's perfect for me, thanks :)
