### ISSUE TITLE
Unicode error in multiline output

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/sobole-zsh-theme#15]
Since last update I have found this little yet annoying bug: after some command exists with non-zero status code my theme looks and feels broken.

Initial view:
<img width="682" alt="2018-11-11 23 18 28" src="https://user-images.githubusercontent.com/4660275/48318143-0ce38200-e60d-11e8-8b94-acb339d2e180.png">

Regular command, works fine:

<img width="682" alt="2018-11-11 23 18 38" src="https://user-images.githubusercontent.com/4660275/48318145-1371f980-e60d-11e8-9501-ac51ac04e23d.png">

Error code is now shown, prompt is broken, note its position:

<img width="682" alt="2018-11-11 23 18 47" src="https://user-images.githubusercontent.com/4660275/48318146-18cf4400-e60d-11e8-8347-42d5db0c6911.png">

It also affect how autocompletion works. Some random chars tend to appear in the suggestions.

I have tested this bug on several terminals, no changes.
Version information: `zsh 5.6.2 (x86_64-apple-darwin15.6.0)`

After some debugging I was able to track down this problem to `:high-voltage-sign:` unicode sing. 
That I use for error status reporting. https://emojipedia.org/high-voltage-sign/

When I delete it, that's what happens:

![2018-11-11 23 43 27](https://user-images.githubusercontent.com/4660275/48318152-2684c980-e60d-11e8-9996-506b621fb39f.png)

Everything looks normal again, spaces are respected.

**Comment by sobolevn** [comment]
So, I have decided to change this sign to ⚠️

**Comment by koloskus** [comment]
I was having what seems to be the same problem you described above with the ⚠️character:

<img width="682" alt="Screen Shot 2019-08-06 at 2 32 13 PM" src="https://user-images.githubusercontent.com/5032045/62566525-27beec00-b857-11e9-8bec-e05e0dd30798.png">

Strangely, I have an older machine that uses zsh 5.2 and copy of the theme from November 2017 that doesn't have this issue, though it uses the ⚡character:

<img width="973" alt="Screen Shot 2019-08-06 at 4 03 15 PM" src="https://user-images.githubusercontent.com/5032045/62573405-00225080-b864-11e9-947d-725dff8bc30a.png">

My newer machine was running zsh 5.3 by default, and the problem with ⚠️ went away after i installed a newer zsh using homebrew:

<img width="682" alt="Screen Shot 2019-08-06 at 3 58 31 PM" src="https://user-images.githubusercontent.com/5032045/62573044-1976cd00-b863-11e9-96fe-971d8fb868c6.png">

Not sure if this is helpful at all, but just in case someone else runs into this problem I thought I'd add that here!

**Comment by sobolevn** [comment]
@koloskus thanks a lot!
