### ISSUE TITLE
not reading my aliases from zshrc file

### ISSUE THREAD

**Issue by nancycg** [sobolevn/sobole-zsh-theme#17]
I really liked this theme...when I applied it on iTerm with oh-my-zsh then all the aliases stopped working.

**Comment by sobolevn** [comment]
What kind of aliases? Do they work with other themes?

**Comment by nancycg** [comment]
aliases added to zshrc file(like a shortcut to run long command). yes working with robbyrussell

**Comment by sobolevn** [comment]
Can you spot a name conflict between your aliases and plugin internals? https://github.com/sobolevn/sobole-zsh-theme
