### ISSUE TITLE
Root prompt not set to #

### ISSUE THREAD

**Issue by wsw70** [sobolevn/sobole-zsh-theme#19]
The prompt for the user `root` is `$` → it should be set to `#` when the `uid` is `0`

**Comment by sobolevn** [comment]
Hi @wsw70!

>  it should be set to # when the uid is 0

Is this a strict rule? Or a well-known convention?

**Comment by wsw70** [comment]
> Is this a strict rule? Or a well-known convention?

I cannot really tell, but in 25 years of administrating UNIX systems I have always seen the `root` prompts as `#`. 

The user's ones vary, but for sh-derived shells (bash, zsh) it was `$` and for csh-derived ones (tcsh, ...) it was `%`.

It is not a "strict rule" because one can change the `PS1` prompt, but I would say that it is a standard. Also see https://unix.stackexchange.com/questions/291729/why-is-the-default-symbol-for-a-user-shell-and-the-default-symbol-for-a-root

**Comment by sobolevn** [comment]
@wsw70 feel free to send a PR with the fix! 👍
