### ISSUE TITLE
GREP_OPTIONS is dreprecated 

### ISSUE THREAD

**Issue by avonheimburg** [sobolevn/sobole-zsh-theme#7]
Since at least GNU grep 2.21, the environment variable GREP_OPTIONS is deprecated. Setting it leads to an error message on theme load and every subsequent grep invocation:

```
» grep --version
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep (GNU grep) 2.25
```
That is quire annoying. The offending entry is around line 150:
```
export GREP_COLOR='1;35'
export GREP_OPTIONS='--color=auto'
```
Please consider removing it and invoking grep directly with the necessary options set.

**Comment by avonheimburg** [comment]
On further investigation, it seems that sobole does not actually need grep_options to be set in order to work.

**Comment by avonheimburg** [comment]
Pull request #8 submitted to fix this issue

**Comment by sobolevn** [comment]
Thanks! Fixed.
